### PR TITLE
Brute force encryption key automatically

### PR DESCRIPTION
**Pull request by ofalvai**
Context: #46 

### Changes

- Remove "Use encryption" and "encryption key" config inputs
- Detect if `?encrypted=1` needed or not for requests
- If needed, brute force encryption key based on the encrypted response
- Also handles the case of #35 where `?encrypted=1` is required but the response is not encrypted, just hex encoded

### CODE REVIEW

**Comment by hellmind** [comment]
What if I want to put it manually

**Comment by ofalvai** [comment]
@hellmind Can you describe why you'd want to provide the key manually?

**Comment by hellmind** [comment]
because I get BAD REQUEST

https://github.com/ofalvai/home-assistant-candy/issues/57

**Comment by Powerdrift777** [comment]
Same issue with HBWOS 69TMET-80 :(

**Pull request merged**
